GET http://localhost:8080/api/car
Accept: application/json

###

GET http://localhost:8080/api/car/1
Accept: application/json

###
GET http://localhost:8080/api/car/find/3
Accept: application/json

###


PUT http://localhost:8080/api/car
Content-Type: application/json

{
  "id": 1,
  "licencePlateNumber": "ter-666",
  "name": "name-11",
  "onwerID": 1,
  "doorNumbers": 0
}

###

DELETE http://localhost:8080/api/car/5
Accept: application/json

###

POST http://localhost:8080/api/car
Content-Type: application/json

{
  "licencePlateNumber": "ter-666",
  "name": "name-11",
  "onwerID": 1,
  "doorNumbers": 0
}

###


